import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import { useEffect } from "react";
import { io } from "socket.io-client";
export default function Home() {
  const { data: sessionData } = useSession();
  console.log(sessionData);
  const a = api.log.live.useSubscription(
    {
      projectId: "HelloWorld",
    },
    {
      onData(data) {
        console.log(data);
      },
      onError(err) {
        console.error(err);
      },
      onStarted() {
        console.log("started");
      },
    },
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid h-screen w-screen place-items-center">
        {sessionData?.user ? (
          <button>Dashboard</button>
        ) : (
          <button onClick={() => void signIn()}>Login</button>
        )}
      </main>
    </>
  );
}
